### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by mepc36** [ashleykleynhans/audiocraft-docker#1]
Hey, just found out about audiocraft/MusicGen 5 minutes ago, and thanks to awesome open source developers like you @ashleykleynhans I can now have it running in my production RunPod environment within another 5 minutes. You're the best! Really, thanks so much.

Just wondering, what's your interest in Audiocraft? Academic? Or do you have a product I could try?

Always trying to learn, thanks again Ashley!

**Comment by ashleykleynhans** [comment]
Hi, you're welcome.  I have not built any products, its just for R&D purposes by seeing what is available and testing out the capabilities to determine whether the project could potentially be useful for something.
